//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentEditor.Resources.DocumentEditor", typeof(DocumentEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table is a great way to organize information with in your document..
        /// </summary>
        internal static string AddTableToolTip {
            get {
                return ResourceManager.GetString("AddTableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Table.
        /// </summary>
        internal static string AddTableToolTipHeader {
            get {
                return ResourceManager.GetString("AddTableToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center your content on the page..
        /// </summary>
        internal static string AlignCenterToolTip {
            get {
                return ResourceManager.GetString("AlignCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center (Ctrl + E).
        /// </summary>
        internal static string AlignCenterToolTipHeader {
            get {
                return ResourceManager.GetString("AlignCenterToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string AlignJustify {
            get {
                return ResourceManager.GetString("AlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute your text evenly between the margin..
        /// </summary>
        internal static string AlignJustifyToolTip {
            get {
                return ResourceManager.GetString("AlignJustifyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify (Ctrl + J).
        /// </summary>
        internal static string AlignJustifyToolTipHeader {
            get {
                return ResourceManager.GetString("AlignJustifyToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align your content with the left margin..
        /// </summary>
        internal static string AlignLeftToolTip {
            get {
                return ResourceManager.GetString("AlignLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left (Ctrl + L).
        /// </summary>
        internal static string AlignLeftToolTipHeader {
            get {
                return ResourceManager.GetString("AlignLeftToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align your content with the right margin..
        /// </summary>
        internal static string AlignRightToolTip {
            get {
                return ResourceManager.GetString("AlignRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right (Ctrl + R).
        /// </summary>
        internal static string AlignRightToolTipHeader {
            get {
                return ResourceManager.GetString("AlignRightToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Templates.
        /// </summary>
        internal static string AvailableTemplates {
            get {
                return ResourceManager.GetString("AvailableTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Document.
        /// </summary>
        internal static string BlankDocument {
            get {
                return ResourceManager.GetString("BlankDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It creates the new empty document..
        /// </summary>
        internal static string BlankDocumentToolTip {
            get {
                return ResourceManager.GetString("BlankDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BlueHighlightToolTip {
            get {
                return ResourceManager.GetString("BlueHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your text bold..
        /// </summary>
        internal static string BoldToolTip {
            get {
                return ResourceManager.GetString("BoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold (Ctrl+B).
        /// </summary>
        internal static string BoldToolTipHeader {
            get {
                return ResourceManager.GetString("BoldToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Green.
        /// </summary>
        internal static string BrightGreenHighlightToolTip {
            get {
                return ResourceManager.GetString("BrightGreenHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Library.
        /// </summary>
        internal static string BulletLibrary {
            get {
                return ResourceManager.GetString("BulletLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create bullet list..
        /// </summary>
        internal static string BulletsToolTip {
            get {
                return ResourceManager.GetString("BulletsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        internal static string BulletsToolTipHeader {
            get {
                return ResourceManager.GetString("BulletsToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the arrow to change look of the bullet..
        /// </summary>
        internal static string BulletsToolTipMore {
            get {
                return ResourceManager.GetString("BulletsToolTipMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put a copy of the selection on the clipboard so you can paste it somewhere else..
        /// </summary>
        internal static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        internal static string CopyToolTipHeader {
            get {
                return ResourceManager.GetString("CopyToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selection and put it on the Clipboard so you can paste it somewhere else..
        /// </summary>
        internal static string CutToolTip {
            get {
                return ResourceManager.GetString("CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        internal static string CutToolTipHeader {
            get {
                return ResourceManager.GetString("CutToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        internal static string DarkBlueHighlightToolTip {
            get {
                return ResourceManager.GetString("DarkBlueHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        internal static string DarkRedHighlightToolTip {
            get {
                return ResourceManager.GetString("DarkRedHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Yellow.
        /// </summary>
        internal static string DarkYellowHighlightToolTip {
            get {
                return ResourceManager.GetString("DarkYellowHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Font.
        /// </summary>
        internal static string DecreaseFont {
            get {
                return ResourceManager.GetString("DecreaseFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your text a bit smaller..
        /// </summary>
        internal static string DecreaseFontSizeToolTip {
            get {
                return ResourceManager.GetString("DecreaseFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Font Size (Ctrl+&amp;lt;).
        /// </summary>
        internal static string DecreaseFontSizeToolTipHeader {
            get {
                return ResourceManager.GetString("DecreaseFontSizeToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move your paragraph closer to the margin..
        /// </summary>
        internal static string DecreaseIndentToolTip {
            get {
                return ResourceManager.GetString("DecreaseIndentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent.
        /// </summary>
        internal static string DecreaseIndentToolTipHeader {
            get {
                return ResourceManager.GetString("DecreaseIndentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define new Multilevel List....
        /// </summary>
        internal static string DefineList {
            get {
                return ResourceManager.GetString("DefineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected comment..
        /// </summary>
        internal static string DeleteCommentToolTip {
            get {
                return ResourceManager.GetString("DeleteCommentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        internal static string DeleteCommentToolTipHeader {
            get {
                return ResourceManager.GetString("DeleteCommentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt with password.
        /// </summary>
        internal static string EncryptWithPassword {
            get {
                return ResourceManager.GetString("EncryptWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password-protect this document..
        /// </summary>
        internal static string EncryptWithPasswordToolTip {
            get {
                return ResourceManager.GetString("EncryptWithPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find text or other content in the document..
        /// </summary>
        internal static string FindToolTip {
            get {
                return ResourceManager.GetString("FindToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl+F).
        /// </summary>
        internal static string FindToolTipHeader {
            get {
                return ResourceManager.GetString("FindToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the color of you text..
        /// </summary>
        internal static string FontColorToolTip {
            get {
                return ResourceManager.GetString("FontColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the size of your text..
        /// </summary>
        internal static string FontSizeToolTip {
            get {
                return ResourceManager.GetString("FontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size (Ctrl+Shift+P).
        /// </summary>
        internal static string FontSizeToolTipHeader {
            get {
                return ResourceManager.GetString("FontSizeToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a new font for your text..
        /// </summary>
        internal static string FontToolTip {
            get {
                return ResourceManager.GetString("FontToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font (Ctrl+Shift+F).
        /// </summary>
        internal static string FontToolTipHeader {
            get {
                return ResourceManager.GetString("FontToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A complete information on Syncfusion RichTextBox control and its usage..
        /// </summary>
        internal static string GettingStartedToolTip {
            get {
                return ResourceManager.GetString("GettingStartedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray-25%.
        /// </summary>
        internal static string Gray25HighlightToolTip {
            get {
                return ResourceManager.GetString("Gray25HighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray-50%.
        /// </summary>
        internal static string Gray50HighlightToolTip {
            get {
                return ResourceManager.GetString("Gray50HighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string GreenHighlightToolTip {
            get {
                return ResourceManager.GetString("GreenHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow Font.
        /// </summary>
        internal static string GrowFont {
            get {
                return ResourceManager.GetString("GrowFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Document.
        /// </summary>
        internal static string HtmlDocument {
            get {
                return ResourceManager.GetString("HtmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file as Html document.
        /// </summary>
        internal static string HtmlDocumentToolTip {
            get {
                return ResourceManager.GetString("HtmlDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a link in your document for quick access to webpage and files..
        /// </summary>
        internal static string HyperlinkToolTip {
            get {
                return ResourceManager.GetString("HyperlinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Hyperlink(Ctrl+K).
        /// </summary>
        internal static string HyperlinkToolTipHeader {
            get {
                return ResourceManager.GetString("HyperlinkToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrations.
        /// </summary>
        internal static string Illustrations {
            get {
                return ResourceManager.GetString("Illustrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your text a bit bigger..
        /// </summary>
        internal static string IncreaseFontSizeToolTip {
            get {
                return ResourceManager.GetString("IncreaseFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Font Size (Ctrl+&gt;).
        /// </summary>
        internal static string IncreaseFontSizeToolTipHeader {
            get {
                return ResourceManager.GetString("IncreaseFontSizeToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move your paragraph farther away from the margin..
        /// </summary>
        internal static string IncreaseIndentToolTip {
            get {
                return ResourceManager.GetString("IncreaseIndentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent.
        /// </summary>
        internal static string IncreaseIndentToolTipHeader {
            get {
                return ResourceManager.GetString("IncreaseIndentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note about this part of the document..
        /// </summary>
        internal static string InsertCommentToolTip {
            get {
                return ResourceManager.GetString("InsertCommentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a Comment.
        /// </summary>
        internal static string InsertCommentToolTipHeader {
            get {
                return ResourceManager.GetString("InsertCommentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italicize your text..
        /// </summary>
        internal static string ItalicToolTip {
            get {
                return ResourceManager.GetString("ItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic (Ctrl+I).
        /// </summary>
        internal static string ItalicToolTipHeader {
            get {
                return ResourceManager.GetString("ItalicToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how much space appears between lines of text..
        /// </summary>
        internal static string LineSpacingToolTip {
            get {
                return ResourceManager.GetString("LineSpacingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Spacing.
        /// </summary>
        internal static string LineSpacingToolTipHeader {
            get {
                return ResourceManager.GetString("LineSpacingToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Library.
        /// </summary>
        internal static string ListLibrary {
            get {
                return ResourceManager.GetString("ListLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a multilevel list to organize items or create an outline..
        /// </summary>
        internal static string MultilevelListToolTip {
            get {
                return ResourceManager.GetString("MultilevelListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilevel List.
        /// </summary>
        internal static string MultilevelListToolTipHeader {
            get {
                return ResourceManager.GetString("MultilevelListToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Pages.
        /// </summary>
        internal static string MultiplePagesView {
            get {
                return ResourceManager.GetString("MultiplePagesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom the document so you can see multiple pages in the window..
        /// </summary>
        internal static string MultiplePagesViewToolTip {
            get {
                return ResourceManager.GetString("MultiplePagesViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        internal static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextComment {
            get {
                return ResourceManager.GetString("NextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to the next comment..
        /// </summary>
        internal static string NextCommentToolTip {
            get {
                return ResourceManager.GetString("NextCommentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Comment.
        /// </summary>
        internal static string NextCommentToolTipHeader {
            get {
                return ResourceManager.GetString("NextCommentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        internal static string NoColor {
            get {
                return ResourceManager.GetString("NoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering Library.
        /// </summary>
        internal static string NumberingLibrary {
            get {
                return ResourceManager.GetString("NumberingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create numbered list..
        /// </summary>
        internal static string NumberingToolTip {
            get {
                return ResourceManager.GetString("NumberingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string NumberingToolTipHeader {
            get {
                return ResourceManager.GetString("NumberingToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the arrow for more numbering formats..
        /// </summary>
        internal static string NumberingToolTipMore {
            get {
                return ResourceManager.GetString("NumberingToolTipMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number alignment: Left.
        /// </summary>
        internal static string NumberLeftAlignment {
            get {
                return ResourceManager.GetString("NumberLeftAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number alignment: Right.
        /// </summary>
        internal static string NumberRightAlignment {
            get {
                return ResourceManager.GetString("NumberRightAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Page.
        /// </summary>
        internal static string OnePageView {
            get {
                return ResourceManager.GetString("OnePageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom the document so that you can see the entire page in window..
        /// </summary>
        internal static string OnePageViewToolTip {
            get {
                return ResourceManager.GetString("OnePageViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        internal static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UG documents helps understanding the usage of our Syncfusion UI components..
        /// </summary>
        internal static string OnlineHelpToolTip {
            get {
                return ResourceManager.GetString("OnlineHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Width.
        /// </summary>
        internal static string PageWidth {
            get {
                return ResourceManager.GetString("PageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom the document so that the width of the page matches the width of the window..
        /// </summary>
        internal static string PageWidthToolTip {
            get {
                return ResourceManager.GetString("PageWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add content on the Clipboard to your document..
        /// </summary>
        internal static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string PasteToolTipHeader {
            get {
                return ResourceManager.GetString("PasteToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert pictures from your computer or from other computers that you&apos;re connected to..
        /// </summary>
        internal static string PictureToolTip {
            get {
                return ResourceManager.GetString("PictureToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File.
        /// </summary>
        internal static string PictureToolTipHeader {
            get {
                return ResourceManager.GetString("PictureToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string PinkHighlightToolTip {
            get {
                return ResourceManager.GetString("PinkHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousComment {
            get {
                return ResourceManager.GetString("PreviousComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to the previous comment..
        /// </summary>
        internal static string PreviousCommentToolTip {
            get {
                return ResourceManager.GetString("PreviousCommentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Comment.
        /// </summary>
        internal static string PreviousCommentToolTipHeader {
            get {
                return ResourceManager.GetString("PreviousCommentToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Layout.
        /// </summary>
        internal static string PrintLayout {
            get {
                return ResourceManager.GetString("PrintLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out how your document will look when it&apos;s printed..
        /// </summary>
        internal static string PrintLayoutToolTip {
            get {
                return ResourceManager.GetString("PrintLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofing.
        /// </summary>
        internal static string Proofing {
            get {
                return ResourceManager.GetString("Proofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Document.
        /// </summary>
        internal static string ProtectDocument {
            get {
                return ResourceManager.GetString("ProtectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control what types of changes people can make to this document..
        /// </summary>
        internal static string ProtectDocumentToolTip {
            get {
                return ResourceManager.GetString("ProtectDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict the content editing and formatting changes..
        /// </summary>
        internal static string ReadOnlyToolTip {
            get {
                return ResourceManager.GetString("ReadOnlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedHighlightToolTip {
            get {
                return ResourceManager.GetString("RedHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl + Y).
        /// </summary>
        internal static string RedoToolTip {
            get {
                return ResourceManager.GetString("RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for text you&apos;d like to change and replace it with something else..
        /// </summary>
        internal static string ReplaceToolTip {
            get {
                return ResourceManager.GetString("ReplaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace (Ctrl+H).
        /// </summary>
        internal static string ReplaceToolTipHeader {
            get {
                return ResourceManager.GetString("ReplaceToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict Editing.
        /// </summary>
        internal static string RestrictEditing {
            get {
                return ResourceManager.GetString("RestrictEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricts editing to this document..
        /// </summary>
        internal static string RestrictEditingToolTip {
            get {
                return ResourceManager.GetString("RestrictEditingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string RibbonStatusBarPage {
            get {
                return ResourceManager.GetString("RibbonStatusBarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        internal static string RibbonStatusBarPageOf {
            get {
                return ResourceManager.GetString("RibbonStatusBarPageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number in document..
        /// </summary>
        internal static string RibbonStatusBarPageToolTip {
            get {
                return ResourceManager.GetString("RibbonStatusBarPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl + S).
        /// </summary>
        internal static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all the comments alongside the document..
        /// </summary>
        internal static string ShowCommentsToolTip {
            get {
                return ResourceManager.GetString("ShowCommentsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        internal static string ShowCommentsToolTipHeader {
            get {
                return ResourceManager.GetString("ShowCommentsToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleStrike.
        /// </summary>
        internal static string SingleStrike {
            get {
                return ResourceManager.GetString("SingleStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling.
        /// </summary>
        internal static string Spelling {
            get {
                return ResourceManager.GetString("Spelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typos? Not on our watch. Let us check your spelling..
        /// </summary>
        internal static string SpellingToolTip {
            get {
                return ResourceManager.GetString("SpellingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling (F7).
        /// </summary>
        internal static string SpellingToolTipHeader {
            get {
                return ResourceManager.GetString("SpellingToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross something out by drawing a line through it..
        /// </summary>
        internal static string StrikethroughToolTip {
            get {
                return ResourceManager.GetString("StrikethroughToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string StrikethroughToolTipHeader {
            get {
                return ResourceManager.GetString("StrikethroughToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubScript.
        /// </summary>
        internal static string SubScript {
            get {
                return ResourceManager.GetString("SubScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type very small letter just just above the line of text..
        /// </summary>
        internal static string SubScriptToolTip {
            get {
                return ResourceManager.GetString("SubScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript (Ctrl+=).
        /// </summary>
        internal static string SubScriptToolTipHeader {
            get {
                return ResourceManager.GetString("SubScriptToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperScript.
        /// </summary>
        internal static string SuperScript {
            get {
                return ResourceManager.GetString("SuperScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type very small letter just above the line of text..
        /// </summary>
        internal static string SuperScriptToolTip {
            get {
                return ResourceManager.GetString("SuperScriptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript (Ctrl+Shift++).
        /// </summary>
        internal static string SuperScriptToolTipHeader {
            get {
                return ResourceManager.GetString("SuperScriptToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string TealHighlightToolTip {
            get {
                return ResourceManager.GetString("TealHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Document.
        /// </summary>
        internal static string TextDocument {
            get {
                return ResourceManager.GetString("TextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file as Text document.
        /// </summary>
        internal static string TextDocumentToolTip {
            get {
                return ResourceManager.GetString("TextDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Highlight Color.
        /// </summary>
        internal static string TextHighlightColor {
            get {
                return ResourceManager.GetString("TextHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your text pop by highlighting it in a bright color..
        /// </summary>
        internal static string TextHighlightColorToolTip {
            get {
                return ResourceManager.GetString("TextHighlightColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string TurquoiseHighlightToolTip {
            get {
                return ResourceManager.GetString("TurquoiseHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline your text..
        /// </summary>
        internal static string UnderlineToolTip {
            get {
                return ResourceManager.GetString("UnderlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline (Ctrl+U).
        /// </summary>
        internal static string UnderlineToolTipHeader {
            get {
                return ResourceManager.GetString("UnderlineToolTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl + Z).
        /// </summary>
        internal static string UndoToolTip {
            get {
                return ResourceManager.GetString("UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncfusion User Interface Help.
        /// </summary>
        internal static string UserInterfaceHelp {
            get {
                return ResourceManager.GetString("UserInterfaceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string VioletHighlightToolTip {
            get {
                return ResourceManager.GetString("VioletHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Layout.
        /// </summary>
        internal static string WebLayout {
            get {
                return ResourceManager.GetString("WebLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how your document would look as a webpage. This layout is also great if you have wide tables in your document..
        /// </summary>
        internal static string WebLayoutToolTip {
            get {
                return ResourceManager.GetString("WebLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word 97 - 2003 Document.
        /// </summary>
        internal static string WordDoc {
            get {
                return ResourceManager.GetString("WordDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a copy as Word 97-2003.
        /// </summary>
        internal static string WordDocToolTip {
            get {
                return ResourceManager.GetString("WordDocToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Document.
        /// </summary>
        internal static string WordDocx {
            get {
                return ResourceManager.GetString("WordDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file as Word document.
        /// </summary>
        internal static string WordDocxToolTip {
            get {
                return ResourceManager.GetString("WordDocxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xaml Document.
        /// </summary>
        internal static string XamlDocument {
            get {
                return ResourceManager.GetString("XamlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file as Xaml document.
        /// </summary>
        internal static string XamlDocumentToolTip {
            get {
                return ResourceManager.GetString("XamlDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string YellowHighlightToolTip {
            get {
                return ResourceManager.GetString("YellowHighlightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string Zoom100 {
            get {
                return ResourceManager.GetString("Zoom100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom your document to 100%..
        /// </summary>
        internal static string Zoom100ToolTip {
            get {
                return ResourceManager.GetString("Zoom100ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the zoom level.
        /// </summary>
        internal static string ZoomInToolTip {
            get {
                return ResourceManager.GetString("ZoomInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the zoom level..
        /// </summary>
        internal static string ZoomOutToolTip {
            get {
                return ResourceManager.GetString("ZoomOutToolTip", resourceCulture);
            }
        }
    }
}
